### ISSUE TITLE
Add templates that use the Poetry packaging system to `pulumi new`

### ISSUE THREAD

**Issue by infin8x** [pulumi/templates#179]
Some Python users prefer the [Poetry packaging system](https://python-poetry.org/) to virtual environments. We should consider adding templates to `pulumi new` that help users successfully configure a Pulumi project using Poetry.

**Comment by AmitArie** [comment]
Any updates?
Thanks!

**Comment by RobbieMcKinstry** [comment]
@kpitzen When you get a chance, do you think you could provide an update on the status of this issue? IIRC your hackathon project had success in this area. TYVM ❤️

**Comment by kpitzen** [comment]
Sorry for missing your ping, @RobbieMcKinstry !  My hackathon project was indeed pointed in this direction, and I would love to have more discussions about how to ship that work.  It breaks some of our current assumptions both in terms of how templates work, _and_ how our runtime manages tooling.  My implementation was relatively quick, and I think I'd rather solve both of these problems in a little bit more future-facing way.  

That being said, I would love to be able to prioritize this :)

**Comment by fsdrw08** [comment]
Any updates?
Thanks!

**Comment by justinvp** [comment]
When creating new projects with `pulumi new` using v3.120.0 or later of the Pulumi CLI, you can choose Poetry. For more details see https://www.pulumi.com/blog/pulumi-loves-python/#native-support-for-poetry.
