### ISSUE TITLE
CI failing for azure template checks

### ISSUE THREAD

**Issue by t0yv0** [pulumi/templates#278]
### What happened?

Something is off with azure template checks.

When merging fix for java templates (not tested yet, TBD) https://github.com/pulumi/templates/pull/276

We noticed that CI failed indicating azure templates checks did not succeed. 

https://github.com/pulumi/templates/runs/6295416238?check_suite_focus=true#step:18:741

### Steps to reproduce

See https://github.com/pulumi/templates/runs/6295416238?check_suite_focus=true#step:18:741

### Expected Behavior

CI passing on PRs

### Actual Behavior

CI failing

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by cnunciato** [comment]
Closing this as we'll cover it with #433.
