### ISSUE TITLE
Switch templates to .NET 6

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/templates#292]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

.NET 6 is the current LTS version. We should switch our templates to .NET 6 and use the latest C# features like top-level statements to make the program as nice and as simple as possible.

**Comment by Zaid-Ajaj** [comment]
Working on it

**Comment by mikhailshilkov** [comment]
Reverted in #300, we need to prep the docs update before we merge again
