### ISSUE TITLE
Very slow 15-20 min azure-{typescript, javascript, python} templates

### ISSUE THREAD

**Issue by t0yv0** [pulumi/templates#298]
### What happened?

Understandably azure-native provider can be large but these timings are suspiciously high. I cannot reproduce such slowdown locally. Historical data indicates the slowdown is in "pulumi new" phase so possibly related to `npm install` and similar. Perhaps the downloads are slower in the CI environment? There was also a significant regression circa Sept 2021 for javascript.

```
TestTemplates/azure-javascript (15m49.79s)
TestTemplates/azure-python (14m48.17s)
TestTemplates/azure-typescript (20m0.01s)
```

### Steps to reproduce

Look at CI timings.

### Expected Behavior

Template tests take under 10 min in GitHub actions.

### Actual Behavior

Template tests take 20-30 min in GitHub actions.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Might have gotten better but still spending minutes in pulumi new, up to 17 min:

https://metabase.corp.pulumi.com/question/1301-pulumi-new-azure-javascript

**Comment by justinvp** [comment]
Closing this old issue as no repro. Times are more reasonable now.

<img width="404" alt="Image" src="https://github.com/user-attachments/assets/cfa3d745-40ce-4ff4-9148-9471cf855003" />
