### ISSUE TITLE
Remove .append files from Pulumi YAML templates

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/templates#325]
As of the following change, the .append file is no longer needed, and YAML templates must record all resources, variables, outputs, and configuration in the Pulumi.yaml file of the template.
- https://github.com/pulumi/pulumi/pull/10401

This change will be shipped in Pulumi 3.39, and by .40 or .41 we can remove the .append files from this repo.

**Comment by cnunciato** [comment]
Hey @AaronFriel, checking in on this one. Is it safe to do this now?
