### ISSUE TITLE
Flesh out template matrix

### ISSUE THREAD

**Issue by justinvp** [pulumi/templates#34]
- [x] go
- [x] javascript
- [x] python
- [x] typescript
- [x] aws-go
- [x] aws-javascript
- [x] aws-python
- [x] aws-typescript
- [ ] azure-go
- [ ] azure-javascript
- [ ] azure-python
- [ ] azure-typescript
- [ ] gcp-go
- [ ] gcp-javascript
- [ ] gcp-python
- [ ] gcp-typescript
- [ ] openstack-go
- [ ] openstack-javascript
- [ ] openstack-python
- [ ] openstack-typescript
- [x] kubernetes-javascript (#36)
- [x] kubernetes-typescript (#33)
- [x] openstack-typescript
- [x] hello-aws-javascript

**Comment by joeduffy** [comment]
I *think* @lukehoban agreed to drive this one from here.
