### ISSUE TITLE
Windows tests failing

### ISSUE THREAD

**Issue by lukehoban** [pulumi/templates#370]
The Windows tests have been failing since https://github.com/pulumi/templates/actions/runs/3039081499/jobs/4893593866.

A subset of the AWS tests fail on Windows with this:

```
  Diagnostics:
    aws:s3:Bucket (my-bucket):
      error: unable to validate AWS credentials. Make sure you have:
      
       	 • Set your AWS region, e.g. `pulumi config set aws:region us-west-2`
       	 • Configured your AWS credentials as per https://pulumi.io/install/aws.html
       	 You can also set these via cli using `aws configure`.
```

Oddly, many of the AWS tests (in fact, the ones added in the that first saw these failures) do succeed.

**Comment by t0yv0** [comment]
https://github.com/pulumi/templates/actions/runs/3039081499/jobs/4893593866#step:18:540

Token expired. Windows tests just happen to run slower. 

https://github.com/pulumi/templates/pull/382#issuecomment-1260971391 addresses this I believe.
