### ISSUE TITLE
Container templates tests failing on Windows and Mac OS

### ISSUE THREAD

**Issue by t0yv0** [pulumi/templates#386]
### What happened?

On windows-latest and macos-latest runners, the container* tests are failing.

Example windows failure (not sure of the root cause):

https://github.com/pulumi/templates/actions/runs/3144242871/jobs/5109989950#step:20:1771

Example mac failure (root cause: no docker command installed):

https://github.com/pulumi/templates/actions/runs/3141813118/jobs/5104676522#step:21:1943

Would it be acceptable to do platform-specific skips for these? Or do we need to figure out how to make them pass on these platforms.

### Steps to reproduce

See CI failures

### Expected Behavior

CI passes

### Actual Behavior

CI fails

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by cnunciato** [comment]
Took a bit to get a Windows machine set up today, but I've confirmed the templates do work on Windows, so at least we know that.

**Comment by t0yv0** [comment]
LMK if I can help with adding skips (perhaps temporarily). It looked like setting up Docker on the workers can be done but is going to be very slow.

**Comment by lukehoban** [comment]
Can we turn off the template tests for these templates only on Mac/windows?
