### ISSUE TITLE
Incorrect "Dev CLI" identified in Run Template Tests Against Latest CLI + Dev CLI 

### ISSUE THREAD

**Issue by t0yv0** [pulumi/templates#388]
### What happened?

https://github.com/pulumi/templates/actions/runs/3141813118/jobs/5104676418

“DEV CLI” is “Currently Pulumi v3.40.0-alpha.1663101047" is installed but 
“Latest CLI” is “Currently Pulumi v3.40.2 is installed”

Therefore container tests fail on "DEV CLI" but pass on "Latest CLI" which actually has the bugfix. 

Given https://github.com/pulumi/pulumi/issues/10728 the identification of "DEV CLI" is incorrect and it's not going to update itself until there's some answer to 10728. 

Perhaps we could skip testing against "DEV CLI" in the meanwhile? 

### Steps to reproduce

https://github.com/pulumi/templates/actions/runs/3141813118/jobs/5104676418 

Observe "Run Template Tests Against Latest CLI + Dev CLI" runs in GHA.

### Expected Behavior

Tests pass on "DEV CLI" after bugfixes land on master in pulumi/pulumi.

### Actual Behavior

"DEV CLI" is stuck on outdated version.

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
CC @cnunciato

**Comment by cnunciato** [comment]
Based on the issue description and linked issue, I'm okay with not testing a dev CLI for the time being.
