### ISSUE TITLE
retrofit go templates with `buildTarget` option

### ISSUE THREAD

**Issue by dixler** [pulumi/templates#392]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Add `buildTarget: a.out` to Pulumi.yaml in go templates to get ~40% reduction in startup time and make pulumi go more quick.

**Comment by scottslowe** [comment]
@dixler Can you provide some additional information? I tried adding this to a Go-based template I'm currently testing and got an error:
```
runtime:
  name: go
  options:
    buildTarget: a.out
```
Am I missing part of what needs to be added/specified?

**Comment by dixler** [comment]
@scottslowe that's weird.

https://github.com/pulumi/pulumi/blob/master/tests/integration/go/go-build-target/Pulumi.yaml

which version of pulumi are you using?

**Comment by scottslowe** [comment]
macOS 12.6 on M1/M1 Pro running Go 1.18.5

Let me try `./a.out` (I had just `a.out` so and it threw a path error, so maybe that's it)

**Comment by dixler** [comment]
that's weird I just ran into this error too.

**Comment by dixler** [comment]
to clarify on the state of this, we're going to wait as adding the `buildTarget` flag crashes older versions of the CLI.

It passes an unexpected command line argument to the language provider which causes it to crash.

**Comment by cnunciato** [comment]
Closing for now, as it sounds like we want to hold off on this. Feel free to reopen if there's more to be done here, though.
