### ISSUE TITLE
Fix YAML warnings

### ISSUE THREAD

**Issue by cnunciato** [pulumi/templates#417]
Seeing these in `azure-yaml`, and presumably any template that uses expressions like these:

![image](https://user-images.githubusercontent.com/274700/197038430-79110719-0a36-4e61-be11-9a8789ea2e95.png)

**Comment by joeduffy** [comment]
I just hit this -- definitely takes away a bit from demoing these schnazzy new templates. Thoughts on when we might fix?

**Comment by cnunciato** [comment]
Indeed. It's on our list for this sprint, so I'm sure we could pick it up next, once these last few templates are wrapped up.
