### ISSUE TITLE
Azure static website template pulls in AWS as a dependency

### ISSUE THREAD

**Issue by joeduffy** [pulumi/templates#430]
I created an Azure static website (`static-website-azure-typescript`), and saw that it installed the AWS Pulumi plugin. That seemed odd to me, but it seems the `@pulumi/synced-folder` package requires it:

```
├─┬ @pulumi/synced-folder@0.0.8
│ │ A Pulumi component that synchronizes a local folder to Amazon S3, Azure Blob Storage, or Google Cloud Storage.
│ │ git+https://github.com/pulumi/pulumi-synced-folder.git
│ │ https://pulumi.com
│ └─┬ @pulumi/aws@5.19.0
│   │ A Pulumi package for creating and managing Amazon Web Services (AWS) cloud resources.
│   │ git+https://github.com/pulumi/pulumi-aws.git
│   │ https://pulumi.io
```

I can guess why this happens (the folder code presumably needs to reference all of the clouds). I wonder if there's any way to avoid that? For instance, perhaps the `synced-folder` package could require AWS, Azure, etc, as a peer dependency, under the theory that if you're deploying to AWS, you're going to have already pulled that package in as the consumer anyway?

It's possible this is just "by design" but it caught me by surprised so I figured I'd open the issue to at least discuss and decide.

**Comment by cnunciato** [comment]
We should probably break these up into separate components. We'll do that and then also look into how best to keep them relatively up to date with current releases of their respective cloud providers.

**Comment by cnunciato** [comment]
Ok, I think I've tracked this down. Looks like it's copy-pasta from the ts-boilerplate repo:

https://github.com/pulumi/pulumi-component-provider-ts-boilerplate/blob/8fdc2ab0142a2a89dabd14fd8cf384910192fef3/sdk/go.mod#L8

I get the same behavior with with the azure-static-website component, which also has this line in sdk/go.mod (and does not use synced-folder):

https://github.com/pulumi/pulumi-azure-static-website/blob/40b55f07fd6c9a35c48887df0d6e4be8dc2f1d8a/sdk/go.mod#L8
