### ISSUE TITLE
Make template tests more resilient

### ISSUE THREAD

**Issue by cnunciato** [pulumi/templates#433]
Our testing situation in this repo still needs work. For one, the tests regularly fail for reasons that aren't related to individual template content (cloud provider quota overages, disk space issues, etc.). Secondly, they take much too long to run, because we test every template in the repository on every change — which is probably unnecessary considering there isn't any shared code between them (CLI release tests being one possible exception to this). 

We should come up with a testing solution that not only fixes these problems and results in the tests passing reasonably quickly and reliably, but that also leaves us room for growth as we continue adding new templates to the mix.

**Comment by cnunciato** [comment]
Initial thoughts:
* On a PR, it's OK to test only the template(s) that are changing
* Should be able to run broader tests on demand via slash-commands
* Need to think through whether/how to test on CLI releases

**Comment by scottslowe** [comment]
A number of PRs have been merged in the last week or so to help with template tests:

* https://github.com/pulumi/templates/pull/494
* https://github.com/pulumi/templates/pull/497
* https://github.com/pulumi/templates/pull/500
* https://github.com/pulumi/templates/pull/506
* https://github.com/pulumi/templates/pull/515

@cnunciato Up to you whether you'd like to mark this complete (and add it to the current milestone for work tracking) or continue to work on this.

**Comment by cnunciato** [comment]
Ha! I was just about to pop in and see whether the work we've done so far meets the bar to close this out. I think it does, since the tests seem to be passing regularly now; we can file follow-ups for further improvements. Sounds like you agree, so I'll close!
