### ISSUE TITLE
serverless-aws-typescript and -csharp templates fail to compile

### ISSUE THREAD

**Issue by cnunciato** [pulumi/templates#469]
Likely related to dependency updates (https://github.com/pulumi/templates/pull/466).

**Comment by cnunciato** [comment]
Looks like the TS failure may be due to `yarn.lock`.

**Comment by cnunciato** [comment]
And now I'm no longer able to repro the issue with Yarn. 😕 Perhaps was just a local environment issue.

**Comment by ajmueller** [comment]
@cnunciato out of curiosity, what issues were you having? I'm trying to get `container-aws-typescript` to run and I get the following on `pulumi up`:

```shell
Diagnostics:
  pulumi:pulumi:Stack (fargate-test-dev):
    node:internal/modules/package_json_reader:4
    const internalModuleReadJSON = function (f) { return require('fs').internalModuleReadJSON(f); };
                                                                       ^
    TypeError: require(...).internalModuleReadJSON is not a function
        at internalModuleReadJSON (node:internal/modules/package_json_reader:4:68)
        at Object.read (node:internal/modules/package_json_reader:21:42)
        at readPackage (node:internal/modules/cjs/loader:296:36)
        at readPackageScope (node:internal/modules/cjs/loader:329:19)
        at trySelf (node:internal/modules/cjs/loader:444:40)
        at Function.Module._resolveFilename (node:internal/modules/cjs/loader:910:24)
        at Function.Module._load (node:internal/modules/cjs/loader:778:27)
        at Module.require (node:internal/modules/cjs/loader:1005:19)
        at Module._preloadModules (node:internal/modules/cjs/loader:1280:12)
        at loadPreloadModules (node:internal/bootstrap/pre_execution:482:5)

  pulumi:providers:awsx (default_1_0_0):
    error: could not read plugin [/Users/alex/.pulumi/plugins/resource-awsx-v1.0.0/pulumi-resource-awsx] stdout: EOF
```

I'm just curious if you were seeing the same thing with the serverless templates since you referred to #466.

**Comment by cnunciato** [comment]
@ajmueller I haven't encountered any issues with the container templates myself. (The issue I saw with `serverless-aws-typescript` had to do with a type mismatch in the program that went away after clearing some cache.) I haven't seen anything like what you have here, though (and unfortunately I don't have an M1 on hand to test with.) I'll see if someone on the team can repro, though.

**Comment by cnunciato** [comment]
@ajmueller We're looking into this now. Mind sharing the output of `pulumi about` here (as run from the root of this Pulumi project)?

**Comment by RobbieMcKinstry** [comment]
I tried to repro on Ventura on an M1 and I was unable to produce the issue :(

**Comment by ajmueller** [comment]
@cnunciato here is the output for `pulumi about`:

```shell
CLI          
Version      3.48.0
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.21.1
awsx    1.0.0
docker  3.6.1
nodejs  unknown

Host     
OS       darwin
Version  13.0.1
Arch     arm64

This project is written in nodejs: executable='/Users/alex/.nvm/versions/node/v16.18.1/bin/node' version='v16.18.1'

Current Stack: dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/ajmueller
User           ajmueller
Organizations  ajmueller, atomicfi

Dependencies:
NAME            VERSION
@pulumi/aws     5.21.1
@pulumi/awsx    1.0.0
@pulumi/pulumi  3.48.0
@types/node     14.18.33
typescript      4.9.3

Pulumi locates its logs in /var/folders/q3/k7n69f4n7dq4vlwnvqd4stkm0000gn/T/ by default
```

As noted in the output here, I am using `nvm` to manage Node versions and have 16.18.1 as my default version.

`package.json` contents in the root are:

```json
{
	"name": "fargate-test",
	"devDependencies": {
		"@types/node": "^14"
	},
	"dependencies": {
		"@pulumi/aws": "^5.21.1",
		"@pulumi/awsx": "^1.0.0",
		"@pulumi/pulumi": "^3.0.0",
		"typescript": "^4.0.0"
	}
}
```

For my `app` directory's `package.json`, I have:

```json
{
  "name": "app",
  "version": "1.0.0",
  "description": "",
  "main": "server.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node server.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "express": "^4.18.2"
  }
}
```

Since this was closed, I'm happy to create a new issue for this since it's specific to `container-aws-typescript` and link back to this one and in there provide a more full example with all of my code (I could put up a repo, too).

**Comment by cnunciato** [comment]
>I'm happy to create a new issue for this

@ajmueller That'd be awesome, if you wouldn't mind. I seem to have all the `pulumi about` details as you do, with the exception of OS version and architecture (and I don't have a Node app in the `app` folder -- just the stock Dockerfile that ships with the template). So this'll probably take a bit more digging.

Thanks for your patience -- we'll get to the bottom of it!

**Comment by ajmueller** [comment]
@cnunciato no problem! I'm actually able to recreate the issue with the stock `container-aws-typescript` template without adding any Node code in the `app` folder and just using the nginx Dockerfile, so I'll just file with that in mind.
