### ISSUE TITLE
Investigate possible issues with serverless-aws-typescript

### ISSUE THREAD

**Issue by cnunciato** [pulumi/templates#538]
Using `serverless-aws-typescript` this weekend, I noticed a few things I wasn't expecting:

Warning when serializing some JS that incorporates the AWS SDK:

<img width="972" alt="image" src="https://user-images.githubusercontent.com/274700/224578200-96487cca-b55e-4190-aa10-43e6a016f0bd.png">

ServerSideEncryption diff when updating the bucket, despite that a new AWS has shipped (so we should be picking it up, but don't seem to be):

<img width="896" alt="image" src="https://user-images.githubusercontent.com/274700/224578248-38c511e1-740d-4a4a-b3e3-b3768e0b4528.png">

Permissions don't seem to allow access to non-HTML files (e.g., CSS, JS, SVG):

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/274700/224578513-4dea1dc5-e15f-44e5-b2a0-ca644322fbf4.png">

Generated `package.json` has whitespace issues:

<img width="595" alt="image" src="https://user-images.githubusercontent.com/274700/224578671-d9149509-1a61-4d4d-aa08-471f66360769.png">

We should investigate these and file issues as necessary.

**Comment by cnunciato** [comment]
Another issue I just noticed when trying to use this template (which I haven't seen before): 

```
Diagnostics:
  aws:apigateway:RestApi (api):
    error: 1 error occurred:
        * creating urn:pulumi:dev::myapp::aws-apigateway:index:RestAPI$aws:apigateway/restApi:RestApi::api: 1 error occurred:
        * error creating API Gateway specification: BadRequestException: Errors found during import:
        Unable to put integration on 'GET' for resource at path '/': Invalid ARN specified in the request
        Unable to put integration on 'GET' for resource at path '/date': Invalid ARN specified in the request
        Unable to put integration on 'ANY' for resource at path '/{proxy+}': Invalid ARN specified in the request
```

**Comment by susanev** [comment]
@cnunciato im rolling this forward to the next iteration; feel free to adjust if that's wrong

**Comment by cnunciato** [comment]
Reviewed today and no longer seeing these issues, so closing.
