### ISSUE TITLE
Update all templates to use Docker provider 4.x

### ISSUE THREAD

**Issue by jkodroff** [pulumi/templates#567]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

At the very least, the Azure Container template is still using version 3.x of the Docker provider. There have been major improvements in version 4.x of the provider, so we should update to the latest major version.

**Comment by scottslowe** [comment]
@mnlumi I don't think `kubernetes-aws-go` is affected. The `container-aws-*` templates, though, do use AWSX.

**Comment by mnlumi** [comment]
@scottslowe I do see the template pulls in docker v3 as an indirect dependency when it runs. This template will need to be updated when awsx is updated in the future. I can put kubernetes-aws-go on a separate issue and leave this one for direct docker v3 updates.

**Comment by scottslowe** [comment]
@mnlumi The `container-azure-*` and `container-gcp-*` templates have been updated (#593 was merged). Do we want to keep this issue open for the `container-aws-*` templates, which use Docker 3.x via AWSX?

**Comment by lukehoban** [comment]
> Do we want to keep this issue open for the container-aws-* templates, which use Docker 3.x via AWSX?

I think we can close this, and track the rest as part of updating awsx to docker v4.
