### ISSUE TITLE
[Node SDK] Add TypeScript and TS-Node explicit imports

### ISSUE THREAD

**Issue by RobbieMcKinstry** [pulumi/templates#583]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

To support https://github.com/pulumi/pulumi/issues/12687 , the Pulumi templates should be updated to explicitly specify versions of TypeScript and TS-Node. This is because in a fewer version of Pulumi, we will mark TypeScript and TS-Node as peer-dependencies. This is technically a breaking change; users who don't have these packages specified in `package.json`, and use particular versions of Yarn Berry or legacy NPM, will get an error (we'll try to mitigate this as well, by intercepting the error ahead of time and improving the error message).

However, if we update the templates to provide these versions, we can prevent this class of error for anyone using the new template.

### Affected area/feature

NodeJS `package.json`

**Comment by scottslowe** [comment]
@RobbieMcKinstry Can you provide an example of what this would look like?

**Comment by julienp** [comment]
We can probably also set `target: es2022` in tsconfig, since our minimum supported node version is now node 18.

**Comment by julienp** [comment]
Done in https://github.com/pulumi/templates/pull/774
