### ISSUE TITLE
SageMaker template causing test failures

### ISSUE THREAD

**Issue by scottslowe** [pulumi/templates#646]
The `sagemaker-aws-python` template is causing test failures because the tests expect no changes, and the Pulumi program reports changes related to the Cloudwatch metrics.

**Comment by scottslowe** [comment]
https://github.com/pulumi/templates/pull/644 provides a short-term fix by unsetting the `important: true` property and therefore bypasses the tests.

**Comment by cnunciato** [comment]
Following up from triage this morning, I think we can close this, yeah -- I've run this several times myself in various ways and always gotten no diff:

![image](https://github.com/pulumi/templates/assets/274700/4a5cc0ea-3f9b-4d54-8e05-734174343ce9)
