### ISSUE TITLE
Several templates still referencing AWS v5

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/templates#657]
Ran into this with the `aws-typescript` template which is very commonly used. Did not exhaustively check all templates, but this query shows four ts/js templates still referencing v5. We should do an audit on other languages as well. 

https://github.com/search?q=repo%3Apulumi%2Ftemplates+%22%40pulumi%2Faws%22+%22%5E5%22&type=code

**Comment by scottslowe** [comment]
Every single example found in that search also pulls in `pulumi/awsx`, which prevents us (currently) from being able to move to AWS v6. When the AWSX v2 upgrade happens, then these templates can be updated.

**Comment by scottslowe** [comment]
It looks like only the following templates are affected:

* aws-fsharp
* aws-visualbasic

**Comment by scottslowe** [comment]
This is fixed by #752, will close this issue once that PR merges

**Comment by scottslowe** [comment]
Fixed via #752 (and a number of other prior PRs)
