### ISSUE TITLE
First sample I tried didn't work

### ISSUE THREAD

**Issue by RustyF** [pulumi/templates#691]
Hi there, I tried the first sample (https://www.pulumi.com/templates/container-service/aws/) and it failed straightaway. I've got the latest .Net SDK installed plus the latest Pulimi 3.86.0. I get this 

Projects/pulumi/my-container-service via .NET v7.0.401 🎯 net6.0 on ☁️  (eu-west-2) took 9s
❯ pulumi up
Previewing update (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/rustyf/bob/dev/previews/75254635-33d8-446c-bc2f-119a6139678f

     Type                                Name            Plan       Info
 +   pulumi:pulumi:Stack                 bob-dev         create     1 error
 +   ├─ awsx:lb:ApplicationLoadBalancer  loadbalancer    create
 +   │  ├─ aws:lb:TargetGroup            loadbalancer    create
 +   │  ├─ aws:ec2:SecurityGroup         loadbalancer    create
 +   │  ├─ aws:lb:LoadBalancer           loadbalancer    create
 +   │  └─ aws:lb:Listener               loadbalancer-0  create
 +   ├─ aws:ecs:Cluster                  cluster         create
 +   ├─ awsx:ecr:Repository              repo            create
 +   │  ├─ aws:ecr:Repository            repo            create
 +   │  └─ aws:ecr:LifecyclePolicy       repo            create
 +   └─ awsx:ecr:Image                   image           create

Diagnostics:
  pulumi:pulumi:Stack (bob-dev):
    error: Running program 'E:\Projects\pulumi\my-container-service\bin\Debug\net6.0\bob.dll' failed with an unhandled exception:
    System.ArgumentNullException: [Input] Pulumi.Awsx.Ecs.Inputs.TaskDefinitionContainerDefinitionArgs.Name is required but was not given a value (Parameter 'Name')
       at Task<ImmutableDictionary<string, object>> Pulumi.InputArgs.ToDictionaryAsync()
       at async Task<ImmutableDictionary<string, object>> Pulumi.Serialization.Serializer.SerializeInputArgsAsync(string ctx, InputArgs args, bool keepResources, bool keepOutputValues)

Looking at the generated C#, I can see that the Container definition doesn't have a Name?

    var service = new Awsx.Ecs.FargateService("service", new()
    {
        Cluster = cluster.Arn,
        AssignPublicIp = true,
        TaskDefinitionArgs = new Awsx.Ecs.Inputs.FargateServiceTaskDefinitionArgs
        {
            Container = new Awsx.Ecs.Inputs.TaskDefinitionContainerDefinitionArgs
            {
/// no name here???
                Image = image.ImageUri,
                Cpu = cpu,
                Memory = memory,
                Essential = true,
                PortMappings = new[]
                {
                    new Awsx.Ecs.Inputs.TaskDefinitionPortMappingArgs
                    {
                        ContainerPort = containerPort,
                        TargetGroup = loadbalancer.DefaultTargetGroup,
                    },
                },
            },
        },
    });

So maybe this is the problem?

**Comment by cleverguy25** [comment]
@cnunciato FYI

**Comment by interurban** [comment]
It seems like this should have been caught by our CI testing, are there changes that need to be made to the tests ?

**Comment by cnunciato** [comment]
@interurban Yes -- we don't (yet) test the architecture templates in CI, and the upgrade to AWSx 2.* was made without adding this now-required property. 

PR inbound.
