### ISSUE TITLE
Do a `dotnet restore` after installing a .NET template

### ISSUE THREAD

**Issue by joeduffy** [pulumi/templates#70]
For symmetry with how other languages work, I believe we ought to be running `dotnet restore` to install packages during template creation. E.g., like [we do with Node.js and NPM](https://github.com/pulumi/templates/issues/6).

**Comment by lukehoban** [comment]
No it’s that unlike other languages - we do a dotnet restore (and dotnet build) as part of `pulumi up`.  

So this is not strictly needed for Pulumi up. But is probably still a good idea for tooling.

**Comment by lukehoban** [comment]
This is also important to move the cost of the "restore" and initial build earlier before the `pulumi up`.  The display during `pulumi up` is much less "nice", and also makes Pulumi itself feel slower the first time if this is delayed past the template creation step.
