### ISSUE TITLE
Templates CI workflow is using an unsupported GH Action for setting up GCP

### ISSUE THREAD

**Issue by scottslowe** [pulumi/templates#753]
### What happened?

I re-ran one of the CI tests for templates PRs and saw this in the logs:

<img width="1252" alt="image" src="https://github.com/pulumi/templates/assets/1977326/2589d9ea-ab3e-4d40-bbae-eb1b166840f4">

### Example

Run the Windows CI test in the templates repository

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
This was fixed by https://github.com/pulumi/templates/pull/805 and no longer repros
